AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

MethodLength:
  Enabled: false
Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false